### PR TITLE
Added pwd

### PR DESCRIPTION
**Pull request by iamthemuffinman**
Initial pwd implementation.

### CODE REVIEW

**Comment by iamthemuffinman** [comment]
I didn't really test this before I submitted it and kinda FUBAR'd it. I'm revising it now.

**Comment by iamthemuffinman** [comment]
Revised.

**Comment by EricLagerg** [comment]
Looks good! There are a couple changes I want to make that I'll probably be able to get around to tomorrow. So, consider it merged as of tomorrow 😀 thanks for your help!

**Comment by EricLagerg** [comment]
A couple of *minor* changes*

**Comment by EricLagerg** [comment]
Also, how would you like your contribution to be listed? Your name or just "and Go-coreutil authors" (or whatever it says right now)?

**Comment by iamthemuffinman** [comment]
You're welcome! I'm pretty excited about a complete Go implementation of GNU coreutils so I'll try and contribute as much as I can. Sure, go ahead and add my name to the contribution list. :smile:

**Comment by EricLagerg** [comment]
I'll make the changes later.

**Comment by EricLagerg** [comment]
Merging PRs is hard :grin:

**Pull request merged**
