### PR TITLE
Basename + Tests

### PR DESCRIPTION
**Pull request by vanhalt**
DONT MERGE!
This branch is for feedback.

- Modified basename.go to use a function with its name in order to be
called from test.
- Created test file with all use cases based on GNU basename command

Test fails pretty bad in this commit. 

Hi @EricLagerg, I am back. Are you looking for an exact translation of basename.c? I can try to reach same output. My concern right now with my tests would be passing flags and how they will be read by the `flag`. What I mean is that I have to read and would like to know what do you have in mind :smile: 

Note: This branch (in the future) is going to address #6

### CODE REVIEW

**Comment by EricLagerg** [comment]
> Are you looking for an exact translation of basename.c?

Something along those lines. It doesn't need to be a complete transliteration, but sometimes that's a bit easier to do than rewriting from scratch :-)

As long as the output is the same, then everything's perfect! (Obviously assuming it doesn't use like 2GB of RAM or do anything funky.)

Also, if it's possible to create a Windows version please do! Windows doesn't need to be the _exact_ same as the Unix version, because there are some obvious differences between the systems, but "close enough" works.

**Comment by vanhalt** [comment]
Notes:

`-f --flag="1st 2nd"`

When parsing `-f <1st arg> <2nd arg> <3rd arg>`, `*flag` only contains `<1st arg>` which forces to parse `<2nd arg> <3rd arg>` using `flag.Args()`.

When using `--flag`, arguments should be splitted as they are received as a single string in `flag`.

Because this limitations that I found, there is an ugly implementation of the -a --multiple flag. Needs refactor. In fact, I don't know if that is a limitation of the *pflag* library or there is something I am missing. Reading GNU's implementation they parse everything space separated and using argument count. Gonna dig a bit more into that.

**Comment by EricLagerg** [comment]
Yeah, this has happened before. I can't remember how I solved it off the top of my head. Let me dig around for a bit and get back to you.

**Comment by vanhalt** [comment]
Tests working, implementation almost similar to GNU one. Besides the issue with the weird workaround for the `pflag`issue, I think this implementation and tests are ok.

Gonna start working in the Windows one.

**Comment by vanhalt** [comment]
Gonna create a new PR with squashed commits. Windows implementation is going to be implemented in another one, since it seems is gonna take me a while :)

**Pull request closed without merging**
